name: Generate Sphinx Documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Copy my folder
          env:
            SRC_FOLDER_PATH: 'docs/_build/html'
            TARGET_BRANCH: 'gh-pages'
          run: |
            files=$(find $SRC_FOLDER_PATH -type f) # get the file list
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git fetch                         # fetch branches
            git checkout $TARGET_BRANCH       # checkout to your branch
            # git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
            git checkout ${GITHUB_REF##*/}
            git add -A
            git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
            # git push origin $TARGET_BRANCH # push to remote branch
            git subtree push --prefix $SRC_FOLDER_PATH origin $TARGET_BRANCH

            
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      #   with:
      #     publish_branch: gh-pages
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./
      #     force_orphan: true
